# Generated by Django 5.1.7 on 2025-06-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpeta', '0003_alter_operador_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='cedula',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='Cédula'),
        ),
    ]
