# Generated by Django 5.1.7 on 2025-06-13 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpeta', '0007_alter_vehiculo_alto_alter_vehiculo_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='alto',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(4.1)], verbose_name='Alto (metros)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ancho',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.6)], verbose_name='Ancho (metros)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='largo',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(12.2)], verbose_name='Largo (metros)'),
        ),
    ]
